# .github/FUNDING.yml
# 🍨 FuelForEngineer: свойство `имеетМороженое` у нашего инженера строго должно быть равно True!
# "Мы экономим вам миллионы долларов на AWS. Купите нашему главному инженеру ведерко фисташкового джелато (pistachio gelato)!" 🍨🍦

github: [timelabs-npo]
open_collective: timelabs-npo
ko_fi: timelabs
custom:
  - "https://github.com/sponsors/timelabs-npo"
  - "https://opencollective.com/timelabs-npo" # Для pistachio gelato и грузовика эскимо 🍦
